### ISSUE TITLE
[BUG] Debug functions

### ISSUE THREAD

**Issue by GigiaJ** [GigiaJ/RSB#1]
The bot debug classes all fail to work correctly. Likely requiring the client panel and such to be drawn and assigned appropriately.

**Comment by vuurman100** [comment]
Any update about this? trying to make a new gui, but cant find anyway to attach to the paint to the botpanel. same for the paint for on scripts

**Comment by GigiaJ** [comment]
`private static String[] constructDebugs() {
		List<String> debugItems = new ArrayList<String>();
		debugItems.add("Hide Toolbar");
		debugItems.add("Hide Log Window");
		debugItems.add("All Debugging");
		debugItems.add("-");
		for (String key : DEBUG_MAP.keySet()) {
			Class<?> el = DEBUG_MAP.get(key);
			if (PaintListener.class.isAssignableFrom(el)) {
				debugItems.add(key);
			}
		}`

**Comment by GigiaJ** [comment]
Okay, so while testing this I came across a far more debilitating issue that prevents me from testing further. Scripts currently don't seem to do _**anything**_. This includes painting.
I did, however, manage to interact with the client and draw text on it, but since scripts are so broken I couldn't really look further into that.

**Comment by vuurman100** [comment]
How did ya draw text to it?
and what do you mean with scripts are broke? havent test much but seems like i can interact with npcs. only like you mention before the turnTo is broke

**Comment by GigiaJ** [comment]
You're getting scripts made in the testsScript to work and interact with npcs?
As for drawing, I simply called upon the client canvas (can't test in scripts because they don't seem to be working) and directly drew on top of it. Not the best way to go about it and if I can get the scripts functional I'll try adding cleaner solution.

**Comment by vuurman100** [comment]
yeay can load script from the testScript folder also .jar and .classes are working for me. interact works, beside that it click to walls ect because the the turnto and onscreen dont work as you know.

but having no problems with loading scripts.

**Comment by GigiaJ** [comment]
Alright, weirdly enough. Scripts seem to be working, but I have to start the script to login, and then stop it and restart for it to actually execute. That said, I tested whether the script could interact with the panels and client and that seemed to work so after I figure out why the script behaves like that I'll try to make a cleaner solution for drawing on the client.

**Comment by vuurman100** [comment]
good to hear its working for you, would love to see a solution for drawing the debug options.

**Comment by GigiaJ** [comment]
![image](https://user-images.githubusercontent.com/18173108/77968188-abc95680-72b4-11ea-95d5-a16a2b32828b.png)

I've managed to get drawing on the screen and tested the FPS function (it isn't properly implemented yet). I'll clean this tidbit up as well as I can and integrate the debug functions properly.

**Comment by vuurman100** [comment]
Nice work, cant wait for it so i can at least see my mouse position. and if the debugger works it will make it more easy to rewrite the api, have the feeling the is much changed in the past months

**Comment by GigiaJ** [comment]
![image](https://user-images.githubusercontent.com/18173108/78082783-db926000-7381-11ea-8961-bf6bd8c83e41.png)

Not completely finished, as I believe some debug functions are still a little broken. Several are working though.

Additionally, 

> This should allow one to create a new listener in a script and add it to the EventManager to draw directly to the screen.

You _in theory_ should be able to draw on the screen with a script doing that.

**Comment by vuurman100** [comment]
You are really doing a great job, will try get used to github. so i can make changes also and send pull.

**Comment by GigiaJ** [comment]
Thanks! Take your time getting used to it and feel free to make changes and pull requests whenever.
I'll certainly appreciate any help I get on this. :)

I've fixed all the TextEvent debug functions. The PaintEvent ones rely on Calculations which _appear_ to be wrong. Hopefully I'll have that fixed soon as well.

**Comment by GigiaJ** [comment]
All debugs work excluding models, webs, and calc test.
Only models and calc test will cause issues currently.

Mouse can still not be enabled or disable and any debug utilizing models will be broken for now. 
Shouldn't affect much, but models won't be outlined.
Hopefully can finish up tomorrow.

**Comment by GigiaJ** [comment]
Closed due to changes in GUI, since most were fixed and the GUI is being moved away from this isn't needed anymore.
