### ISSUE TITLE
Any plans

### ISSUE THREAD

**Issue by vuurman100** [GigiaJ/RSB#18]
Do you have any plans on updating?

**Comment by GigiaJ** [comment]
TL;DR: **Yes**
I wasn't really expecting anyone to have any vested interest in this, but I did have plans to return to this and my software reversing very soon. 
I do believe the API _should_ mostly work. I got it to the point of functionality and sort of stopped. I didn't develop any scripts for it, but I can probably pretty easily finish polishing it up and craft a few example ones. 
Glad to see interest though, thanks!

**Comment by vuurman100** [comment]
Do you have discord?
