### ISSUE TITLE
[QUESTION] Scripts in testScript package aren't appearing in script selector

### ISSUE THREAD

**Issue by vuurman100** [GigiaJ/RSB#25]
**Propose your question**
Scripts under testScript folder not showing up in script selector, am i doing something wrong?

will try to see if i can make a nice gui if i have time

**Comment by GigiaJ** [comment]
Nope! 

If I remember correctly, this is part of an issue I mean to fix. I didn't open an issue on it, but I certainly should. 
The script has to be compiled (read turned into a class file) which can be done within the IDE and then moved into the scripts folder under GService
I don't recall if the package declaration is suppose to be there, but I'm thinking not.
Seriously, my bad.
I do mention it in the readme

> Currently optimizations are needed for creating/compiling scripts as the best solution is to place them into testScript and compile them there and go to the intellij(or other IDE) directory and drag the class file to the bot's script 


_Also forgive me for the absolutes in path names, when testing it was less of a pain._

**Comment by GigiaJ** [comment]
I've updated the wiki with instructions on how to create scripts at the moment and have a solution made that'll allow future scripts to be made and tested in the testsScript package. I'll push that sometime later today and close this issue then.
