### ISSUE TITLE
[BUG] Scripts failing to execute on first run

### ISSUE THREAD

**Issue by GigiaJ** [GigiaJ/RSB#32]
**BEFORE REPORTING**
Ensure RuneLite is up to date in IDE and you are using the latest version of the master branch

**Describe the bug**
Scripts currently aren't executing any code written in them or the getBot function is returning null values.

**To Reproduce**
1. Create any script with code to be executed.
2. Watch it fail to do anything.

**Expected behavior**
It should execute the code. Additionally, at the moment I am uncertain if the issue lies in the scripts themselves or elsewhere

**Screenshots**
![image](https://user-images.githubusercontent.com/18173108/77865943-d8229b80-71fe-11ea-86c7-49377601bf00.png)

**Desktop (please complete the following information):**

**Additional context**
Found while attempting to fix #1 
Scripts appear to not be able to interact with any given object after getBot() which results in virtually everything written in them failing to run.

**Comment by vuurman100** [comment]
you only should use bot.getMethodContext() from the runelitetestfeature when loading with runelite.
For scripts use ctx.client, and it should fix the problem

**Comment by GigiaJ** [comment]
Thanks for that. I believe it works either way, but doing it that way _IS_ the correct way to prevent errors. 
I've found the issue though. When you initialize a script at the login screen the login script goes off and it never escapes so it stays stuck in the loop.

**Comment by GigiaJ** [comment]
Fixed.
