### ISSUE TITLE
[QUESTION]Anyway you could help?

### ISSUE THREAD

**Issue by vuurman100** [GigiaJ/RSB#42]
I am trying to implent my own gui.

but i am really struggle how the botpanel/bothome are working with the client panel.
Could you help me with make it work? i know i could easy copy/paste most but try to learn something also.

Is there anyway to come in private contact with you? if you are willing to help.

**Comment by GigiaJ** [comment]
Of course! I'm more than happy to help and explain how stuff works in the API. I actually tutor part-time on Java so hopefully I can help.

https://discord.gg/VfKU9eW feel free to join this discord server _it's freshly created so only I'm in it_
