### ISSUE TITLE
[QUESTION] rswidgets: how to debug them

### ISSUE THREAD

**Issue by Jsteem** [GigiaJ/RSB#78]
@GigiaJ 
About the login: are all the login elements also widgets? When i use the developers modus in runelite for examining the widgets, the login field and password field won't show up. Also is it possible to iterate through the worlds and get information about the amount of players, the membership requirement and other reqs? How would you debug the widgets because i don't see any tools other than the built-in runelite dev tool.

Thanks for the information and the interesting project.

**Comment by GigiaJ** [comment]
A year late, but the built-in RuneLite tools *are* enough. Usually. I mean I could only improve them minorly. Ideally, widgets could be tracked by behavior identification (for example, what they do or how they do it and then getting the value by identifying those aspects).
Login elements are not widgets. 
Iterating over worlds should be possible, and I know of a plugin within RuneLite that does so.
