### ISSUE TITLE
REVIVE PROJECT

### ISSUE THREAD

**Issue by GigiaJ** [GigiaJ/RSB#79]
Currently, the project is quite out of date, but I have plans to begin updating it once again soon hopefully.

**Comment by Nubebuster** [comment]
Any updates on it?

**Comment by GigiaJ** [comment]
I haven't forgotten! Just last week I made some rather large changes to another one of my codebases and prepped a solution to finish up another. Once I wrap up those two tasks I'll probably jump back into this and look into both making it functional again, as well as modernizing the code a bit. (Seriously, the lack of comments, iffy modularity, and zero testing is pretty rough.)

**Comment by dAtiuyy** [comment]
Watch this bad boy get a lot of people banned 🤩

**Comment by GigiaJ** [comment]
Hopefully not. Closing issue to clean up issue list
