### ISSUE TITLE
What is the status on this project? [QUESTION]

### ISSUE THREAD

**Issue by smeyerhot** [GigiaJ/RSB#80]
**Propose your question**

How am I suppose to run this project? 
```
gradle run --bot-runelite
``` 
yields the following error:
```
A problem occurred evaluating root project 'RSBBB'.
> Could not find method compile() for arguments [{group=net.runelite, name=client, version=1.6.35}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

In general, are you planning on any further development? If so, I am interested in working on some starting tickets to better understand the project.

**Comment by smeyerhot** [comment]
So, I figured out it was a gradle issue and got the project built. Still, I am unclear on how this project is suppose to be run.

**Comment by GigiaJ** [comment]
Launch it via the RuneLite class' main method.
The logout icon is a placeholder for the script section. (Odds are there are outdated features for sure.) I do plan to resume progress on sometime soon. If I had to guess RuneLite is causing some incompatibilities as it is almost a year out of date. Assuming it does work correctly you'll need to change the dependency to be the latest version of RuneLite (because it will build with an outdated RuneLite version. They host past versions too.) Feel free to ask questions. I'll do my best to answer.

**Comment by smeyerhot** [comment]
Yea, I think there are quite a few breaking changes introduced by the Runelite API. I can't build the project with the new Runelite version.

I am also trying to run from command line because intellij is complaining about the 
```
import lombok.extern.slf4j.Slf4j;
```
log functionality.

**Comment by smeyerhot** [comment]
Do you have a slack or discord server for this project? I would be interested in doing some dev work once the project is useable again/to help get it into that state but I don't really know enough about the project to implement the changes needed for the new runelite version. I am a person who learns by doing and when I can’t get the project to run it’s hard to learn. Let me know if you want to set up a discord/slack server if you don’t have one and maybe we can work together to revitalize this.

**Comment by smeyerhot** [comment]
Btw do you use IntelliJ? I am wondering if you get the Lombok log error as well when you try to run the main Runelite class.

**Comment by Phnmz** [comment]
@GigiaJ Please update this, i'm having a hard time to update this by myself unfortunately.. :(

**Comment by GigiaJ** [comment]
I'll begin prepping an environment to start looking at what needs fixing right now and see if I can get this project back into working order.

I'm a bit busy currently with prepping for company interviews so I can make a living doing what I love. I also have obligations for working on a few of my other projects, but I can add this one to the mix to tinker on. 

If anyone is interested in supporting the project going forward I can start setting up a discord for quicker communication with me.

**Comment by GigiaJ** [comment]
https://discord.gg/CGBXNrHREP
Discord link for the interested

**Comment by GigiaJ** [comment]
The project is now in a functional state (I'm not sure the degree of bugginess, but I'll begin to look into them in the very near future).
